spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:tcp://localhost/~/alog
    username: sa
    password:
    dirver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #show_sql: true
        format_sql: true

  profiles:
    include: oauth

  session:
    store-type: jdbc

server:
  servlet:
    encoding:
      force-response: true