
spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:tcp://localhost/~/alog
    username: sa
    password:
    dirver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  profiles:
    include:
      - oauth
      - mail

  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always

  servlet:
    multipart:
      enabled: true #파일 업로드 가능 여부
      location: C:\\project-upload\\alog
      max-request-size: 30MB
      max-file-size: 10MB

server:
  servlet:
    encoding:
      force-response: true

  error:
    include-exception: true
    include-stacktrace: always
    include-binding-errors: always
    include-message: always
    path: /api/v1/auth/error
    white:
      enabled: false

logging:
  level:
    org:
      hibernate:
        type: trace